apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-operator
  template:
    metadata:
      labels:
        app: hello-world-operator
    spec:
      serviceAccountName: hello-world-operator
      containers:
        - name: manager
          image: vorozhko/hello-world-k8s-operator:latest
          imagePullPolicy: Always
          command:
            - /usr/local/bin/hello-world-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"