apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: helloworlds.example.com
spec:
  group: example.com
  names:
    kind: HelloWorld
    listKind: HelloWorldList
    plural: helloworlds
    singular: helloworld
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
                  description: "The message to be displayed by the HelloWorld resource."
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            message:
              type: string
              minLength: 1
              description: "The message to be displayed by the HelloWorld resource."